localstack_endpoint    = "http://localhost:4566"
aws_region             = "us-west-1"
cron_schedule          = "rate(1 minute)"
github_owner           = "krasovsky22"
github_repo            = "github-activity-tracker"
github_branch          = "main"
github_token_ssm_param = "/github-activity-tracker/github-token"
